### ISSUE TITLE
Mod Conflicts with Pause Button Functionality

### ISSUE THREAD

**Issue by rubiidev18alt** [TechStudent10/ButtonSFX#1]
This issue reports a potential conflict between the "Button SFX" mod for the Geode mod loader and the pause button functionality on mobile devices in Geometry Dash. When the Button SFX mod is active and a level is loaded, users are unable to pause the game by tapping the pause button.

There are two possible explanations for this behavior:

1. **Touch Registration Interference:** The Button SFX mod might be introducing an unintended interaction with the game's UI, causing user touch input to pass through the pause button without registering.
2. **Mod Functionality Override:** The mod's functionality might unintentionally override the built-in pause button functionality, rendering it unresponsive on mobile devices.

This bug significantly impacts gameplay on mobile devices by disabling the crucial pause function.

## Steps to Reproduce

1. Install the Geode mod loader and the Button SFX mod.
2. **Restart Geometry Dash** to allow the mods to load properly.
3. Launch Geometry Dash on a mobile device.
4. Load any level.
5. Attempt to pause the game by tapping the pause button.

**Expected Result:** The game should pause upon tapping the pause button.

**Actual Result:** The pause button does not register the touch input, and the game continues to run.

## Additional info
I am currently using the most recent development build (nightly) of the Geode mod loader, alongside approximately 50 additional mods.

**Comment by TechStudent10** [comment]
What OS are you on? (Windows, MacOS, or Android)

**Comment by rubiidev18alt** [comment]
> What OS are you on? (Windows, MacOS, or Android)

Android.

**Comment by rubiidev18alt** [comment]
Nevermind, was just a bug on qolmod 1.2.9, sorry for posting the issue for this mod, updated qol to 1.3.0 and its fixed.

**Comment by TechStudent10** [comment]
> Nevermind, was just a bug on qolmod 1.2.9, sorry for posting the issue for this mod, updated qol to 1.3.0 and its fixed.

Ah all good
